name: fling_gallery
description: "A Flutter layout widget that positions its children in tight rows."
version: 0.2.0
homepage: https://fling-gallery-demo.web.app/
repository: https://github.com/mongoose13/fling-gallery
issue_tracker: https://github.com/mongoose13/fling-gallery/issues
funding:
  - https://www.paypal.com/paypalme/BruceSantier
topics:
  - photography

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
