name: Validate library quality

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@ce3cf2160d822f73fcb0cf0a8fb549a85e464eab

      - name: Run tests
        run: make test

      - name: Run pana
        run: make pana
